/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-10 03:50:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ggul.zip.tiper.TiperVO;

public final class tiperLessonMake_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ggul.zip.tiper.TiperVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

TiperVO tiperVO = (TiperVO) request.getAttribute("tiperGo");

boolean cateCheck1 = true;
boolean cateCheck2 = true;
String style1 = null;
String style2 = null;

if (tiperVO.getTiper_cate2() == null) {
	cateCheck1 = false;
	if (tiperVO.getTiper_cate3() == null) {
		cateCheck2 = false;
	}
}
if (cateCheck1 == false) {

	style1 = "display: none;";

}

if (cateCheck2 == false) {

	style2 = "display: none;";

}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>강의 등록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/bootstrap.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	#lesmake_sub1 {\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_tab {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_imgdiv {\r\n");
      out.write("		width: 500px;\r\n");
      out.write("		height: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_img {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	#preview {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 300px;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	.lesmake_tr {\r\n");
      out.write("		height: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_info {\r\n");
      out.write("		border: 0;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 300px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_info:focus {\r\n");
      out.write("		border: 3px solid #FFD400;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_title {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("		border: 0;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_title:focus {\r\n");
      out.write("		border: 3px solid #FFD400;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	.lesmake_td1 {\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		text-decoration: underline;\r\n");
      out.write("		text-decoration-color: #FFD400;\r\n");
      out.write("		width: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_cate {\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		margin-left: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_btn1 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		height: 55px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_div2 {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("	#lesmake_sub1 {\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_tab {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_imgdiv {\r\n");
      out.write("		width: 500px;\r\n");
      out.write("		height: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_img {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	#preview {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 300px;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	.lesmake_tr {\r\n");
      out.write("		height: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_info {\r\n");
      out.write("		border: 0;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 300px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_info:focus {\r\n");
      out.write("		border: 3px solid #FFD400;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_title {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("		border: 0;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_title:focus {\r\n");
      out.write("		border: 3px solid #FFD400;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	.lesmake_td1 {\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		text-decoration: underline;\r\n");
      out.write("		text-decoration-color: #FFD400;\r\n");
      out.write("		width: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_cate {\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		margin-left: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_btn1 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		height: 55px;\r\n");
      out.write("	}\r\n");
      out.write("	#lesmake_div2 {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<span id=\"lesmake_sub1\">TIPer 강의 등록</span> <br>\r\n");
      out.write("		<hr>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form action=\"lessonMakeAction\">\r\n");
      out.write("			<div id=\"lesmake_imgdiv\">\r\n");
      out.write("				<input type=\"file\" accept=\".jpg,.jpeg,.png\" name=\"lesson_img\"\r\n");
      out.write("					id=\"lesmake_img\" onchange=\"previewImage(event)\"> <img\r\n");
      out.write("					id=\"preview\" src=\"#\" alt=\"강의사진을 올려주세요\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<table id=\"lesmake_tab1\">\r\n");
      out.write("				<tr class=\"lesmake_tr\">\r\n");
      out.write("					<td class=\"lesmake_td1\">강의 제목</td>\r\n");
      out.write("					<td class=\"lesmake_td2\"><input type=\"text\" name=\"lesson_title\"\r\n");
      out.write("						placeholder=\"강의제목을 입력해주세요\" id=\"lesmake_title\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"lesmake_tr\">\r\n");
      out.write("					<td class=\"lesmake_td1\">강의 내용</td>\r\n");
      out.write("					<td class=\"lesmake_td2\"><textarea name=\"lesson_info\"\r\n");
      out.write("							id=\"lesmake_info\" cols=\"30\" rows=\"10\" placeholder=\"강의내용을 입력해주세요\"></textarea></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"lesmake_tr\">\r\n");
      out.write("					<td class=\"lesmake_td1\">강의 카테고리</td>\r\n");
      out.write("					<td class=\"lesmake_td2\"><select name=\"lesson_cate\"\r\n");
      out.write("						id=\"lesmake_cate\">\r\n");
      out.write("							<option selected disabled hidden>강의 카테고리 선택</option>\r\n");
      out.write("							<option value=\"");
      out.print(tiperVO.getTiper_cate1());
      out.write('"');
      out.write('>');
      out.print(tiperVO.getTiper_cate1());
      out.write("</option>\r\n");
      out.write("							<option style=\"");
      out.print(style1);
      out.write("\" value=\"");
      out.print(tiperVO.getTiper_cate2());
      out.write('"');
      out.write('>');
      out.print(tiperVO.getTiper_cate2());
      out.write("</option>\r\n");
      out.write("							<option style=\"");
      out.print(style2);
      out.write("\" value=\"");
      out.print(tiperVO.getTiper_cate3());
      out.write('"');
      out.write('>');
      out.print(tiperVO.getTiper_cate3());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("					</select></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<br> <br> <br>\r\n");
      out.write("			<div id=\"lesmake_div2\">\r\n");
      out.write("				<button type=\"submit\" id=\"lesmake_btn1\">강의등록하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function previewImage(event) {\r\n");
      out.write("			var reader = new FileReader();\r\n");
      out.write("			reader.onload = function() {\r\n");
      out.write("				var output = document.getElementById('preview');\r\n");
      out.write("				output.src = reader.result;\r\n");
      out.write("			}\r\n");
      out.write("			reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("			// 파일 선택 후 input 요소 숨기기\r\n");
      out.write("			var input = document.getElementById('lesmake_img');\r\n");
      out.write("			input.style.display = 'none';\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
