/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-10 07:07:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ggul.zip.tiper.TiperVO;

public final class tiperMypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682297696099L));
    _jspx_dependants.put("jar:file:/C:/Springwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/honeytiper999/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ggul.zip.tiper.TiperVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int point = (int) session.getAttribute("user_point");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>강사 마이페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/bootstrap.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	#mytip_sub1 {\r\n");
      out.write("		font-size: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_sub2 {\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_sub3 {\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point1 {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point2 {\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point3 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_table1 {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_tr1 {\r\n");
      out.write("		border-bottom: 2px solid #d8dee5;\r\n");
      out.write("		height: 70px;\r\n");
      out.write("	}\r\n");
      out.write("	.my_singo2 {\r\n");
      out.write("		width: 20px;\r\n");
      out.write("		height: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td1 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td2 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td3 {\r\n");
      out.write("		width: 110px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td4 {\r\n");
      out.write("		width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_btn1 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_btn2 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 170px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_btn3 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 170px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		    margin-left: 160px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_sub1 {\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_sub2 {\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		font-size: 28px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		font-size: 28px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_sub3 {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point1 {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point2 {\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_point3 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_table1 {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_tr1 {\r\n");
      out.write("		border-bottom: 2px solid #d8dee5;\r\n");
      out.write("		height: 90px;\r\n");
      out.write("		font-size: 22px;\r\n");
      out.write("	}\r\n");
      out.write("	.my_singo2 {\r\n");
      out.write("		width: 30px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td1 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		width: 250px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td2 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td3 {\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_td4 {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	.mytip_btn1 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_btn2 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 250px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytip_btn3 {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 250px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("		margin-left: 600px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h4 id=\"mytip_sub1\">TIPer마이페이지(강사)</h4>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<div id=\"mytip_sub2\">\r\n");
      out.write("			<span id=\"mytip_sub3\">진행중인 꿀TIP</span><br> <span>강의종료 후\r\n");
      out.write("				완료를 누르시면 회원이 리뷰를 남길 수 있습니다</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div id=\"mytip_point1\">\r\n");
      out.write("			<p id=\"mytip_point2\">\r\n");
      out.write("				<span id=\"mytip_point3\">My허니페이 ");
      out.print(point);
      out.write(" point\r\n");
      out.write("				</span>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<table id=\"mytip_table1\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<button type=\"button\" onclick=\"location.href='honeyTake'\"\r\n");
      out.write("			id=\"mytip_btn2\">허니페이 정산하기</button>\r\n");
      out.write("		<button type=\"button\" onclick=\"location.href='lessonMakeGo'\"\r\n");
      out.write("			id=\"mytip_btn3\">강의등록하기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/tiper/tiperMypage.jsp(188,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/tiper/tiperMypage.jsp(188,3) '${lessonTiper}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lessonTiper}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/tiper/tiperMypage.jsp(188,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("lesson");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<tr class=\"mytip_tr1\">\r\n");
            out.write("					<td class=\"mytip_td1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					<td class=\"mytip_td2\">\r\n");
            out.write("						<div>회원ID: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					</td>\r\n");
            out.write("					<td class=\"mytip_td3\"><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\r\n");
            out.write("					<td class=\"mytip_td4\"><button type=\"button\" onclick=\"\"\r\n");
            out.write("							class=\"mytip_btn1\">수강완료</button></td>\r\n");
            out.write("					<td><img src=\"front/siren.png\" alt=\"신고\"\r\n");
            out.write("						class=\"my_singo2\"></td>\r\n");
            out.write("				</tr>\r\n");
            out.write("\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
