/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-09 04:08:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ggul.zip.user.UserVO;
import com.ggul.zip.tiper.TiperVO;

public final class userMyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/user/../main/footer.jsp", Long.valueOf(1683599073415L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682297696099L));
    _jspx_dependants.put("jar:file:/C:/Springwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/honeytiper999/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ggul.zip.tiper.TiperVO");
    _jspx_imports_classes.add("com.ggul.zip.user.UserVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int point = (int) session.getAttribute("user_point");

// TiperVO tiperVO = (TiperVO) request.getAttribute("myTiper");

// if (tiperVO.getTiper_agree() == 0) {
// 	out.println("<script>");
// 	out.println("alert('승인대기 중입니다. 조금만 더 기다려 주세욧!');");
// 	out.println("history.back();");
// 	out.println("</script>");
// }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"front/bootstrap.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"front/jquery-3.6.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	#sub_1 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		display: block;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_2 {\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_3 {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_point {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("	}\r\n");
      out.write("	#tip_img1 {\r\n");
      out.write("		width: 70px;\r\n");
      out.write("		height: 70px;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#fileModal {\r\n");
      out.write("		width: 75px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		font-size: 5px;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#mypage_tab {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#myimg_singo {\r\n");
      out.write("		width: 20px;\r\n");
      out.write("		height: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_1 {\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_2 {\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_3 {\r\n");
      out.write("		width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_4 {\r\n");
      out.write("		width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_tr {\r\n");
      out.write("		border-bottom: 2px solid #d8dee5;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		width: 80vw;\r\n");
      out.write("	}\r\n");
      out.write("	#my_hr1 {\r\n");
      out.write("		height: 2px;\r\n");
      out.write("	}\r\n");
      out.write("	.modal {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 0;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		display: none;\r\n");
      out.write("		background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("	}\r\n");
      out.write("	.modal .modal-window {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		width: 90vw;\r\n");
      out.write("		height: 50%;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		text-align: center !important;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		margin-top: 20vh;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		align-content: space-around;\r\n");
      out.write("		height: 15%;\r\n");
      out.write("		margin: 0 30px;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title h3 {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin: 10 !important;\r\n");
      out.write("		display: inline;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 85%;\r\n");
      out.write("		border-style: none;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#text_container pre {\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content img {\r\n");
      out.write("		width: 30px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_img_container {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_img_box {\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_radio_container {\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		width: 70%;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_radio_box {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_button_box {\r\n");
      out.write("		margin: 10px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_button_box button {\r\n");
      out.write("		margin: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	#review_text {\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 20px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	#btn_submit {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	#btn_close {\r\n");
      out.write("		background-color: #d8dee5;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.modal .modal-window-singo {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		width: 90vw;\r\n");
      out.write("		height: 50%;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		text-align: center !important;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		margin-top: 20vh;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title-singo {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		align-content: space-around;\r\n");
      out.write("		height: 15%;\r\n");
      out.write("		margin: 0 30px;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title-singo h3 {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin: 10 !important;\r\n");
      out.write("		display: inline;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content-singo {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 85%;\r\n");
      out.write("		border-style: none;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_1 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		display: block;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_2 {\r\n");
      out.write("		font-size: 38px;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_3 {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		font-size: 38px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#sub_point {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#tip_img1 {\r\n");
      out.write("		width: 100px;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#fileModal {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		display: inline;\r\n");
      out.write("	}\r\n");
      out.write("	#mypage_tab {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_1 {\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_2 {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_3 {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_4 {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_5 {\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#mytab_tr {\r\n");
      out.write("		border-bottom: 3px solid #d8dee5;\r\n");
      out.write("		height: 200px;\r\n");
      out.write("		width: 80vw;\r\n");
      out.write("	}\r\n");
      out.write("	#my_hr1 {\r\n");
      out.write("		height: 3px;\r\n");
      out.write("	}\r\n");
      out.write("	#myimg_singo {\r\n");
      out.write("		width: 30px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.modal {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 0;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		display: none;\r\n");
      out.write("		background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("	}\r\n");
      out.write("	.modal .modal-window {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		width: 70vw;\r\n");
      out.write("		height: 60%;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		margin-top: 20vh;\r\n");
      out.write("		margin-right: 10vw;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		align-content: space-around;\r\n");
      out.write("		height: 15%;\r\n");
      out.write("		margin: 0 30px;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#modal-title h3 {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin: 10 !important;\r\n");
      out.write("		display: inline;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border-radius: 20%;\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 85%;\r\n");
      out.write("		border-style: none;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	#text_container pre {\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content img {\r\n");
      out.write("		width: 40px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_img_container {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_img_box {\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_radio_container {\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		width: 70%;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_radio_box {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_button_box {\r\n");
      out.write("		margin: 10px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	#sugar_button_box button {\r\n");
      out.write("		margin: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	#review_text {\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 20px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("	}\r\n");
      out.write("	.rev_span {\r\n");
      out.write("		font-size: 27px;\r\n");
      out.write("	}\r\n");
      out.write("	#btn_submit {\r\n");
      out.write("		background-color: #FFD400;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		font-size: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	#btn_close {\r\n");
      out.write("		background-color: #d8dee5;\r\n");
      out.write("		border: 0;\r\n");
      out.write("		border-radius: 10%;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		font-size: 25px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<p id=\"sub_1\">마이페이지</p>\r\n");
      out.write("		<span id=\"sub_2\">진행중인 Tip</span>\r\n");
      out.write("		<p id=\"sub_3\">\r\n");
      out.write("			<span id=\"sub_point\"> My허니페이 ");
      out.print(point);
      out.write("point\r\n");
      out.write("			</span>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\" id=\"div_tab1\">\r\n");
      out.write("		<table>\r\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<!-- 리뷰 하기 모달창 -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal review1\">\r\n");
      out.write("		<div class=\"modal-window\">\r\n");
      out.write("			<div id=\"modal-title\">\r\n");
      out.write("				<h3>리뷰 작성</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("				<div id=\"text_container\">\r\n");
      out.write("\r\n");
      out.write("					<span class=\"rev_span\">꿀TIP 잘 전수 받으셨나요?</span> <br> <span\r\n");
      out.write("						class=\"rev_span\">잘 받으셨다면 리뷰 작성 부탁드립니다!</span> <br> <span\r\n");
      out.write("						class=\"rev_span\">꿀TIPer에게 큰 도움이 됩니다.</span> <br> <br> <span\r\n");
      out.write("						class=\"rev_span\">도움이 되신 만큼 '당도'를 평가해주세요!</span>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<form action=\"reviewAction\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"sugar_img_container\">\r\n");
      out.write("						<div id=\"sugar_img_box\">\r\n");
      out.write("							<img src=\"front/honeycomb.png\" alt=\"이미지 경로를 설정해주세요!\"> X5 <input\r\n");
      out.write("								type=\"radio\" name=\"review_sugar\" value=\"5\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"sugar_img_box\">\r\n");
      out.write("							<img src=\"front/honeycomb.png\" alt=\"이미지 경로를 설정해주세요!\"> X4 <input\r\n");
      out.write("								type=\"radio\" name=\"review_sugar\" value=\"4\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"sugar_img_box\">\r\n");
      out.write("							<img src=\"front/honeycomb.png\" alt=\"이미지 경로를 설정해주세요!\"> X3 <input\r\n");
      out.write("								type=\"radio\" name=\"review_sugar\" value=\"3\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"sugar_img_box\">\r\n");
      out.write("							<img src=\"front/honeycomb.png\" alt=\"이미지 경로를 설정해주세요!\"> X2 <input\r\n");
      out.write("								type=\"radio\" name=\"review_sugar\" value=\"2\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"sugar_img_box\">\r\n");
      out.write("							<img src=\"front/honeycomb.png\" alt=\"이미지 경로를 설정해주세요!\"> X1 <input\r\n");
      out.write("								type=\"radio\" name=\"review_sugar\" value=\"1\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"hidden\" name=\"review_lesson_num\" id=\"lessonNum\">\r\n");
      out.write("					<input type=\"text\" name=\"review_cont\" id=\"review_text\"\r\n");
      out.write("						placeholder=\"한 줄 리뷰를 작성해주세요\" />\r\n");
      out.write("					<div id=\"sugar_button_box\">\r\n");
      out.write("						<button type=\"submit\" id=\"btn_submit\">리뷰등록</button>\r\n");
      out.write("						<button type=\"button\" id=\"btn_close\">닫기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 신고하기 모달창  -->\r\n");
      out.write("	<div class=\"modal\" id=\"modalSingo\">\r\n");
      out.write("		<div class=\"modal-window-singo\">\r\n");
      out.write("			<div id=\"modal-title-singo\">\r\n");
      out.write("				<h3>신고 하기</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"modal-content-singo\">\r\n");
      out.write("\r\n");
      out.write("				<div id=\"text_container-singo\">\r\n");
      out.write("\r\n");
      out.write("					<span class=\"rev_span\">신고를 하시기 전에!</span> <br> <span\r\n");
      out.write("						class=\"rev_span\">한번 더 생각 해주세요!</span> <br> <span\r\n");
      out.write("						class=\"rev_span\">허위 신고를 할 경우</span> <br> <br> <span\r\n");
      out.write("						class=\"rev_span\">그 사람에게 큰 상처가 될 수 있습니다.</span>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<form action=\"singoAction\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"user_singo1\">\r\n");
      out.write("						<input type=\"text\" placeholder=\"신고내용을 입력해주세요!\" id=\"singo_input1\"\r\n");
      out.write("							name=\"report_cont\"> <input type=\"hidden\"\r\n");
      out.write("							name=\"review_lesson_num\" id=\"lessonNum_singo\">\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"sugar_button_box\">\r\n");
      out.write("				<button type=\"submit\" id=\"btn_submit_singo\">신고하기</button>\r\n");
      out.write("				<button type=\"button\" id=\"btn_close_singo\">닫기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write(" \r\n");
      out.write(" @media ( max-width : 768px) {\r\n");
      out.write(" 	.flex-container{\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .foot_text{\r\n");
      out.write(" color: rgb(255, 255, 255); \r\n");
      out.write(" font-size:11px;\r\n");
      out.write(" margin-right:170px;\r\n");
      out.write(" font-family:Arial, Helvetica, sans-serif;\r\n");
      out.write(" }\r\n");
      out.write(".flex-container {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: stretch;\r\n");
      out.write(" background-color: #212a30;\r\n");
      out.write(" text-align: center;\r\n");
      out.write(" margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </style>   \r\n");
      out.write(" <br><br><br><br><br><br>\r\n");
      out.write("<div class=\"flex-container\">\r\n");
      out.write("  <div style=\"flex-grow: 1\">\r\n");
      out.write("  <br><br>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div style=\"flex-grow: 9\" class=\"foot_text\">\r\n");
      out.write("    <br><br><br><br><br>\r\n");
      out.write("   <p style=\"font-size:13px; font-family:Arial, Helvetica, sans-serif;\">장승무 오현민 김보영 양소연 이승희 정성현 한상현 해애언</p>\r\n");
      out.write("   <p style=\"font-size:13px; font-family:Arial, Helvetica, sans-serif;\">현재 사이트는 교육용으로 제작된 웹 사이트로 실제로 사용이 불가능 합니다\r\n");
      out.write("   \r\n");
      out.write("   	<a href=\"adminLoginBtn\">관리자로그인</a>\r\n");
      out.write("   </p>\r\n");
      out.write("   <p>Copyright © 2023 honeytiper</p>\r\n");
      out.write("   <br><br><br>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    	const modal = document.querySelector('.modal');\r\n");
      out.write("    	const btnFileModal = document.querySelector('.fileModal');\r\n");
      out.write("    	const btnModalClose = document.querySelector('#btn_close');\r\n");
      out.write("    	const btnModalCloseSingo = document.querySelector('#btn_close_singo');\r\n");
      out.write("    	\r\n");
      out.write("    		//리뷰창 강의 번호 주기 함수\r\n");
      out.write("    		function hsh(val) {\r\n");
      out.write("    			modal.style.display='block';\r\n");
      out.write("    	        document.body.style.overflow = 'hidden';\r\n");
      out.write("    	       	document.getElementById(\"lessonNum\").value = val;\r\n");
      out.write("			}\r\n");
      out.write("    	\r\n");
      out.write("    		//신고창 강의 번호 주기 함수\r\n");
      out.write("    		function hsh2(val) {\r\n");
      out.write("    			modal.style.display='block';\r\n");
      out.write("    	        document.body.style.overflow = 'hidden';\r\n");
      out.write("    	       	document.getElementById(\"lessonNum_singo\").value = val;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("    	//리뷰창 닫기\r\n");
      out.write("    	btnModalClose.addEventListener('click', () => {\r\n");
      out.write("    	modal.style.display='none';\r\n");
      out.write("    	});\r\n");
      out.write("    	// 신고창 닫기\r\n");
      out.write("    	btnModalCloseSingo.addEventListener('click', () => {\r\n");
      out.write("        	modal.style.display='none';\r\n");
      out.write("        	});\r\n");
      out.write("    	\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/user/userMyPage.jsp(438,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/user/userMyPage.jsp(438,3) '${lessonList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lessonList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/user/userMyPage.jsp(438,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("lesson");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<tr id=\"mytab_tr\">\r\n");
            out.write("					<td id=\"mytab_1\"><img alt=\"강사이미지\"\r\n");
            out.write("						src=\"front/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"tip_img1\"></td>\r\n");
            out.write("					<td id=\"mytab_2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					<td id=\"mytab_3\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ lesson.lesson_info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					<td id=\"mytab_4\"><button type=\"button\" id=\"fileModal\"\r\n");
            out.write("							class=\"fileModal\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("							onclick=\"hsh(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">수강완료</button></td>\r\n");
            out.write("					<td id=\"mytab_5\"><img src=\"front/siren.png\" alt=\"신고\"\r\n");
            out.write("						class=\"fileModal_singo\" onclick=\"hsh2(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lesson.lesson_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\"\r\n");
            out.write("						id=\"myimg_singo\"></td>\r\n");
            out.write("				</tr>\r\n");
            out.write("\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
