/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-10 05:33:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userTiperSignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");

int check = (int) request.getAttribute("tiperCheck");

if (check == 1) {
	out.println("<script>");
	out.println("alert('승인 대기중입니다!')");
	out.println("location.href='../index';");
	out.println("</script>");

}

      out.write("\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Tiper신청</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"front/common.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"front/bootstrap.css\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( max-width : 768px) {\n");
      out.write("	.container {\n");
      out.write("		width: 100%;\n");
      out.write("	}\n");
      out.write("	#sin_sub1 {\n");
      out.write("		font-size: 28px;\n");
      out.write("		background-color: #FFD400;\n");
      out.write("		border-radius: 10%;\n");
      out.write("	}\n");
      out.write("	#sin_sub2 {\n");
      out.write("		font-size: 20px;\n");
      out.write("	}\n");
      out.write("	#sin_div1 {\n");
      out.write("		width: 200px;\n");
      out.write("		height: 200px;\n");
      out.write("	}\n");
      out.write("	#sin_img1 {\n");
      out.write("		width: 80px;\n");
      out.write("		height: 80px;\n");
      out.write("	}\n");
      out.write("	#sin_info1 {\n");
      out.write("		width: 95%;\n");
      out.write("		border: 0;\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	#sin_info1:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_cate1:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_cate2:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_cate3:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_btn1 {\n");
      out.write("		background-color: #FFD400;\n");
      out.write("		border: 0;\n");
      out.write("		width: 200px;\n");
      out.write("		height: 30px;\n");
      out.write("		border-radius: 10%;\n");
      out.write("	}\n");
      out.write("	#div_btn1 {\n");
      out.write("		text-align: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#tiperUppreview {\n");
      out.write("		width: 200px;\n");
      out.write("		height: 200px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 769px) {\n");
      out.write("	.container {\n");
      out.write("		width: 100%;\n");
      out.write("	}\n");
      out.write("	#sin_sub1 {\n");
      out.write("		font-size: 38px;\n");
      out.write("		background-color: #FFD400;\n");
      out.write("		border-radius: 10%;\n");
      out.write("	}\n");
      out.write("	#sin_sub2 {\n");
      out.write("		font-size: 28px;\n");
      out.write("	}\n");
      out.write("	#sin_img1 {\n");
      out.write("		width: 300px;\n");
      out.write("		height: 80px;\n");
      out.write("	}\n");
      out.write("	#sin_div1 {\n");
      out.write("		width: 300px;\n");
      out.write("		height: 300px;\n");
      out.write("	}\n");
      out.write("	#sin_img1 {\n");
      out.write("		width: 300px;\n");
      out.write("		height: 50px;\n");
      out.write("	}\n");
      out.write("	#sin_info1 {\n");
      out.write("		width: 95%;\n");
      out.write("		height:\n");
      out.write("	}\n");
      out.write("	#sin_info1:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("		font-size: 20px;\n");
      out.write("	}\n");
      out.write("	#sin_cate1, #sin_cate2, #sin_cate3 {\n");
      out.write("		width: 180px;\n");
      out.write("		height: 40px;\n");
      out.write("	}\n");
      out.write("	#sin_cate1:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_cate2:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_cate3:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#sin_btn1 {\n");
      out.write("		background-color: #FFD400;\n");
      out.write("		border: 0;\n");
      out.write("		width: 300px;\n");
      out.write("		height: 50px;\n");
      out.write("		border-radius: 10%;\n");
      out.write("	}\n");
      out.write("	#div_btn1 {\n");
      out.write("		text-align: center;\n");
      out.write("	}\n");
      out.write("	#sin_sub3 {\n");
      out.write("		font-size: 25px;\n");
      out.write("	}\n");
      out.write("	#sin_addr1 {\n");
      out.write("		width: 300px;\n");
      out.write("		height: 40px;\n");
      out.write("	}\n");
      out.write("	#sin_addr1:focus {\n");
      out.write("		border: 3px solid #FFD400;\n");
      out.write("		outline: none;\n");
      out.write("	}\n");
      out.write("	#tiperUppreview {\n");
      out.write("		width: 250px;\n");
      out.write("		height: 250px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<span id=\"sin_sub1\">TIPer 신청</span> <br> <br> <span\n");
      out.write("			id=\"sin_sub2\">카테고리 심사 후 TIPer 등록이 완료됩니다</span> <br>\n");
      out.write("		<hr>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<form action=\"tiperSignUp\" enctype=\"multipart/form-data\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div id=\"sin_div1\">\n");
      out.write("				<input type=\"file\" id=\"sin_img1\" accept=\".jpg,.jpeg,.png\"\n");
      out.write("					placeholder=\"눌러서 강사에 대한 img등록\" name=\"tiper_img\" required=\"required\"\n");
      out.write("					onchange=\"previewImage(event)\"> <img id=\"tiperUppreview\"\n");
      out.write("					src=\"#\" alt=\"강의사진을 올려주세요\">\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			<textarea name=\"tiper_info\" id=\"sin_info1\" cols=\"30\" rows=\"10\"\n");
      out.write("				placeholder=\"TIPer소개를 작성해주세요 (경력, 수상내역, 취득자격증 등등)\"\n");
      out.write("				required=\"required\"></textarea>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<br>\n");
      out.write("		<div class=\"container\">\n");
      out.write("\n");
      out.write("			<p id=\"sin_sub2\">\n");
      out.write("				꿀TIP을 전수해줄 카테고리를 선택해주세요<span style=\"font-size: 12px; color: gray;\">(최대\n");
      out.write("					3개)</span>\n");
      out.write("			</p>\n");
      out.write("			<div id=\"sin_sel1\">\n");
      out.write("				<label for=\"category\"> <select name=\"tiper_cate1\"\n");
      out.write("					id=\"sin_cate1\" required=\"required\">\n");
      out.write("						<option selected disabled hidden>첫번째 카테고리</option>\n");
      out.write("						<option value=\"예체능\">예체능</option>\n");
      out.write("						<option value=\"공예\">공예</option>\n");
      out.write("						<option value=\"사무\">사무</option>\n");
      out.write("						<option value=\"라이프스타일\">라이프스타일</option>\n");
      out.write("						<option value=\"IT\">IT</option>\n");
      out.write("						<option value=\"기타\">기타</option>\n");
      out.write("				</select>&nbsp; <select name=\"tiper_cate2\" id=\"sin_cate2\">\n");
      out.write("						<option selected disabled hidden>두번째 카테고리</option>\n");
      out.write("						<option value=\"예체능\">예체능</option>\n");
      out.write("						<option value=\"공예\">공예</option>\n");
      out.write("						<option value=\"사무\">사무</option>\n");
      out.write("						<option value=\"라이프스타일\">라이프스타일</option>\n");
      out.write("						<option value=\"IT\">IT</option>\n");
      out.write("						<option value=\"기타\">기타</option>\n");
      out.write("				</select>&nbsp; <select name=\"tiper_cate3\" id=\"sin_cate3\">\n");
      out.write("						<option selected disabled hidden>세번째 카테고리</option>\n");
      out.write("						<option value=\"예체능\">예체능</option>\n");
      out.write("						<option value=\"공예\">공예</option>\n");
      out.write("						<option value=\"사무\">사무</option>\n");
      out.write("						<option value=\"라이프스타일\">라이프스타일</option>\n");
      out.write("						<option value=\"IT\">IT</option>\n");
      out.write("						<option value=\"기타\">기타</option>\n");
      out.write("				</select>\n");
      out.write("\n");
      out.write("				</label>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<br>\n");
      out.write("\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<p id=\"sin_sub3\">꿀TIP을 전수해줄 지역을 정확히 입력해주세요</p>\n");
      out.write("			<span style=\"font-size: 10px; color: gray;\">(해당지역 검색에 노출됩니다)</span> <br>\n");
      out.write("			<input type=\"text\" name=\"tiper_addr\" id=\"sin_addr1\"\n");
      out.write("				placeholder=\"활동지역(시)\" required=\"required\">\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<br> <br>\n");
      out.write("		<div id=\"div_btn1\">\n");
      out.write("			<button type=\"submit\" id=\"sin_btn1\">TIPer등록 신청하기</button>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		\n");
      out.write("\n");
      out.write("	$(() => {\n");
      out.write("   $(\"#sin_img1 input[type=file]\").change(function(){\n");
      out.write("      console.log($('#sin_img1 input[type=file]')[0].files);\n");
      out.write("      \n");
      out.write("      let formData = new FormData();\n");
      out.write("      formData.append('tiper_img', $('#sin_img1 input[type=file]')[0].files[0]);\n");
      out.write("      $.ajax({\n");
      out.write("         url : \"/upload\",\n");
      out.write("         type : \"post\",\n");
      out.write("         data : formData,\n");
      out.write("         contentType: false,\n");
      out.write("         processData: false,\n");
      out.write("         cache : false,\n");
      out.write("         success : function(sin_img1){\n");
      out.write("            console.log('success');\n");
      out.write("         },\n");
      out.write("         error : function(){\n");
      out.write("            alert('error');\n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("   });\n");
      out.write("});\n");
      out.write("	\n");
      out.write("	function previewImage(event) {\n");
      out.write("		var reader = new FileReader();\n");
      out.write("		reader.onload = function() {\n");
      out.write("			var output = document.getElementById('tiperUppreview');\n");
      out.write("			output.src = reader.result;\n");
      out.write("		}\n");
      out.write("		reader.readAsDataURL(event.target.files[0]);\n");
      out.write("		// 파일 선택 후 input 요소 숨기기\n");
      out.write("		var input = document.getElementById('sin_img1');\n");
      out.write("		input.style.display = 'none';\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
